// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYK0AAqgOTI7ta-oRwBiV7iuq47uyaKmM',
    appId: '1:270592354754:web:701ae99a9e9f5cd4bfce5b',
    messagingSenderId: '270592354754',
    projectId: 'yell-edb81',
    authDomain: 'yell-edb81.firebaseapp.com',
    storageBucket: 'yell-edb81.firebasestorage.app',
    measurementId: 'G-NVP89GR68D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0K4KHWk6CYFqAzMQFQuHYiKJEMV2swc',
    appId: '1:270592354754:android:7e54cd7197599f36bfce5b',
    messagingSenderId: '270592354754',
    projectId: 'yell-edb81',
    storageBucket: 'yell-edb81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaX9N-tTwPKwl7zCC0pUnHXmv3ysg92A',
    appId: '1:270592354754:ios:c4341be5f910a1b2bfce5b',
    messagingSenderId: '270592354754',
    projectId: 'yell-edb81',
    storageBucket: 'yell-edb81.firebasestorage.app',
    iosBundleId: 'com.example.yell',
  );
}
